# Generated by Django 3.2.16 on 2024-03-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
