# Generated by Django 3.2.16 on 2024-02-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0002_rename_description_position_position_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='short_manifesto',
            field=models.TextField(default='pls vote for me bro!*insert sad face emoji'),
        ),
    ]
