# Generated by Django 3.2.16 on 2024-03-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0005_auto_20240215_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='postion_id',
            new_name='position_id',
        ),
    ]
