# Generated by Django 3.2.16 on 2024-02-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='description',
            new_name='position_description',
        ),
    ]
