# Generated by Django 3.2.16 on 2024-03-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20240315_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousvoter',
            name='ip_address',
            field=models.IntegerField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
