# Generated by Django 3.2.16 on 2024-02-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_candidate_short_manifesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='student_id',
            new_name='student',
        ),
    ]
