# Generated by Django 3.2.16 on 2024-03-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_anonymousvoter_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousvoter',
            name='ip_address',
            field=models.CharField(max_length=100),
        ),
    ]
