# Generated by Django 3.2.16 on 2024-03-17 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_student_candidate_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voters', to='polls.AnonymousVoter'),
        ),
    ]
