# Generated by Django 3.2.16 on 2024-03-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_postion_id_candidate_position_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
