# Generated by Django 3.2.16 on 2024-03-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_candidate_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
    ]
